services:
  dnsdist:
    restart: always
    image: ccr.ccs.tencentyun.com/karasu/stck:dnsdist-2.1.0-rc1
    build:
      context: .
      dockerfile: ./dnsdist-build/Dockerfile
    network_mode: host
    volumes:
      - ./dnsdist:/etc/dnsdist:ro

  # Rule Builder - 域名列表生成器
  rule-builder:
    # profiles:
    #   - rule-builder
    image: ccr.ccs.tencentyun.com/karasu/stck:rule-builder-latest
    build:
      context: .
      dockerfile: ./rule-builder/Dockerfile
    restart: "no"
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - ./:/workdir
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    working_dir: /workdir
    command: ["sleep", "infinity"]
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.refresh.schedule: "0 3 * * *"
      ofelia.job-exec.refresh.command: "python3 rule-builder/rule_builder.py"

  # Ofelia - 定时任务调度
  ofelia:
    restart: always
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock

  # Ansible - 初始化任务，仅在 init profile 运行
  ansible-init:
    profiles:
      - init
    image: alpine/ansible:2.18.6
    restart: "no"
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      # - ./ansible:/ansible:ro
      - ./:/workdir
    working_dir: /workdir
    command: ansible-playbook /workdir/ansible/playbook.yml
